'use client';

import { useState } from 'react';
import { ExternalLink, Plus } from 'lucide-react';

interface Citation {
  citationNumber: number;
  title: string;
  authors: string;
  year: number;
  journal: string;
  pmid: string | null;
  doi: string | null;
  specificFinding: string;
  source: 'database' | 'llm_generated';
}

interface CitationReferencesProps {
  citations: Citation[];
  recommendationRank: number;
}

export default function CitationReferences({ citations, recommendationRank }: CitationReferencesProps) {
  const [addingToDatabase, setAddingToDatabase] = useState<number | null>(null);

  // Debug logging
  console.log(`CitationReferences for rank ${recommendationRank}:`, citations);

  if (!citations || citations.length === 0) {
    console.log(`No citations to display for rank ${recommendationRank}`);
    return null;
  }

  const handleAddToDatabase = (citation: Citation) => {
    setAddingToDatabase(citation.citationNumber);

    // Build query parameters for pre-populating the citation upload form
    const params = new URLSearchParams();
    params.append('title', citation.title);
    params.append('authors', citation.authors);
    params.append('year', citation.year.toString());
    params.append('journal', citation.journal);
    if (citation.pmid) params.append('pmid', citation.pmid);
    if (citation.doi) params.append('doi', citation.doi);
    params.append('keyFindings', citation.specificFinding);
    params.append('source', 'llm_generated');

    // Open in new tab
    window.open(`/admin/citations?${params.toString()}`, '_blank');

    // Reset after a delay
    setTimeout(() => setAddingToDatabase(null), 2000);
  };

  const showAddButton = (citation: Citation) => {
    return citation.source === 'llm_generated';
  };

  return (
    <div className="mt-4 p-4 bg-gray-50 border border-gray-200 rounded-lg">
      <h4 className="font-semibold text-sm mb-3 text-gray-900">References</h4>
      <div className="space-y-3">
        {citations.map((citation) => (
          <div key={citation.citationNumber} className="text-sm">
            <div className="flex items-start justify-between gap-3">
              <div className="flex-1">
                <span className="font-medium text-gray-900">[{citation.citationNumber}]</span>
                <span className="ml-2 text-gray-700">
                  {citation.authors} ({citation.year}). {citation.title}. <em>{citation.journal}</em>.
                </span>
                {citation.pmid && (
                  <a
                    href={`https://pubmed.ncbi.nlm.nih.gov/${citation.pmid}/`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="ml-2 text-primary-600 hover:text-primary-700 inline-flex items-center"
                  >
                    PMID: {citation.pmid}
                    <ExternalLink className="w-3 h-3 ml-1" />
                  </a>
                )}
                {citation.doi && (
                  <a
                    href={`https://doi.org/${citation.doi}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="ml-2 text-primary-600 hover:text-primary-700 inline-flex items-center"
                  >
                    DOI: {citation.doi}
                    <ExternalLink className="w-3 h-3 ml-1" />
                  </a>
                )}
                {citation.specificFinding && (
                  <div className="mt-1 text-xs text-gray-600 pl-6">
                    <strong>Finding:</strong> {citation.specificFinding}
                  </div>
                )}
              </div>

              {showAddButton(citation) && (
                <button
                  onClick={() => handleAddToDatabase(citation)}
                  disabled={addingToDatabase === citation.citationNumber}
                  className="flex-shrink-0 px-3 py-1.5 text-xs font-medium text-primary-700 bg-primary-50 border border-primary-200 rounded hover:bg-primary-100 transition-colors disabled:opacity-50 inline-flex items-center gap-1.5"
                  title="If you have reviewed this citation and believe it to be correct, please consider adding it to our database for more reliable outputs in the future."
                >
                  <Plus className="w-3 h-3" />
                  {addingToDatabase === citation.citationNumber ? 'Opening...' : 'Add to database?'}
                </button>
              )}
            </div>
          </div>
        ))}
      </div>

      {citations.some(c => c.source === 'llm_generated') && (
        <div className="mt-4 p-3 bg-blue-50 border border-blue-200 rounded text-xs text-blue-900">
          <strong>Note:</strong> Citations marked with "Add to database?" were generated by the AI. If you have reviewed these citations and believe they are correct, please consider adding them to our database for more reliable future outputs. This is voluntary.
        </div>
      )}
    </div>
  );
}
